import type { Metadata } from "next";
import Link from "next/link";
import { Arrow, SiteFooter, SiteHeader } from "@/components/site-chrome";
import { researchAreas } from "@/lib/editorial";
import { siteNexisLinks } from "@/lib/site-links";

export const metadata: Metadata = { title: "Research", description: "The NexisHub research agenda across artificial intelligence, search intelligence, education technology, HCI, automation, and knowledge systems.", alternates: { canonical: "/research" } };

export default function ResearchPage() {
  return <><SiteHeader light /><main className="research-page"><section className="research-hero"><div className="shell"><p className="kicker">NexisHub Research</p><h1>Understand deeply.<br /><span>Build responsibly.</span></h1><p>Research at NexisHub studies how intelligent systems can become more useful, explainable, and human-centered across the product ecosystem.</p><div className="research-status"><span>Research agenda</span><strong>Open</strong><span>Publication archive</span><strong>Awaiting first reviewed paper</strong></div></div></section>
      <section className="research-agenda"><div className="shell"><div className="research-heading"><div><p className="kicker">The research agenda</p><h2>Eight connected fields.</h2></div><p>These are durable areas of inquiry, not claims that NexisHub has already published findings in each field.</p></div><div className="research-grid">{researchAreas.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="research-method"><div className="shell"><div><p className="kicker kicker--light">Research method</p><h2>Evidence before announcements.</h2></div><div className="research-steps"><span><b>01</b>Observe the real system</span><span><b>02</b>Frame a testable question</span><span><b>03</b>Experiment within clear boundaries</span><span><b>04</b>Validate, review, and document</span><span><b>05</b>Publish what survives scrutiny</span></div></div></section>
      <section className="research-principles"><div className="shell research-principles-grid"><div><p className="kicker">Research principles</p><h2>Intelligence with integrity.</h2></div><div><article><h3>Explainability</h3><p>A useful result should reveal how it was formed and where uncertainty remains.</p></article><article><h3>Human checkpoints</h3><p>Review requirements scale with consequence; higher-risk outputs demand stronger oversight.</p></article><article><h3>Context isolation</h3><p>Shared intelligence does not mean leaking one product&apos;s data or context into another.</p></article><article><h3>Applied relevance</h3><p>Research earns priority when it can improve a real product, workflow, or decision.</p></article></div></div></section>
      <section className="research-output"><div className="shell research-output-grid"><div><p className="kicker">Applied work</p><h2>A methodology already in production.</h2><p>SiteNexis is the first public example: its documented approach connects technical crawl signals, entity intelligence, retrieval behavior, and machine-trust formation.</p><a className="button" href={siteNexisLinks.methodology} data-analytics="research-sitenexis-methodology">Read the methodology <Arrow /></a></div><div className="research-archive"><span>Publication archive</span><h3>No reviewed NexisHub papers published yet.</h3><p>The archive will list real titles, authors, dates, methods, and revisions when approved work exists.</p><Link href="/blog">Visit the editorial platform <Arrow /></Link></div></div></section>
    </main><SiteFooter /></>;
}
