import type { Metadata } from "next";
import Link from "next/link";
import { Arrow, SiteFooter, SiteHeader } from "@/components/site-chrome";

export const metadata: Metadata = {
  title: "Pnyx | NexisHub",
  description: "Pnyx is a technology knowledge network where technology conversations become organised knowledge.",
  alternates: { canonical: "/products/pnyx" },
};

export default function PnyxPage() {
  const schema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "Pnyx", applicationCategory: "Knowledge network", description: "Where technology conversations become organised knowledge.", url: "https://pnyx-psi.vercel.app", brand: { "@type": "Brand", name: "NexisHub" } };
  return <><SiteHeader light /><main className="article-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} /><header className="article-hero"><div className="shell article-hero-inner"><nav className="article-breadcrumb" aria-label="Breadcrumb"><Link href="/">NexisHub</Link><span>/</span><Link href="/products">Products</Link><span>/</span><span>Pnyx</span></nav><p className="eyebrow"><span /> NexisHub flagship product</p><h1>Pnyx<br /><em>Technology knowledge network.</em></h1><p className="article-deck">Where technology conversations become organised knowledge.</p><div className="article-byline"><span>Status: Live</span><span>Flagship product</span><span>Public profile: Initial</span></div></div></header><div className="shell article-layout"><aside className="article-toc"><p>Product record</p><nav aria-label="Product sections"><a href="#overview">Overview</a><a href="#status">Status</a><a href="#boundaries">Public record</a></nav></aside><article className="article-body"><section id="overview"><h2>Overview</h2><p>Pnyx is a NexisHub flagship product positioned as a technology knowledge network. Its public description is intentionally limited to the verified positioning currently available.</p></section><section id="status"><h2>Product status</h2><p><strong>Live:</strong> The supplied public URL responded successfully during verification.</p><p><strong>Flagship:</strong> Pnyx is part of the NexisHub flagship product ecosystem alongside SiteNexis.</p><p><strong>Product URL:</strong> <a href="https://pnyx-psi.vercel.app" target="_blank" rel="noopener noreferrer">pnyx-psi.vercel.app</a></p></section><section id="boundaries"><h2>Public record boundaries</h2><p>This page does not claim specific features, users, adoption, outcomes, integrations, funding, partnerships, or research findings. Those details require an approved product brief or verified public source.</p><div className="article-callout"><strong>Profile status</strong><p>Initial public product profile. Additional product documentation will be added when verified information is available.</p></div></section><section className="article-product"><span>NexisHub products</span><h2>Explore the wider ecosystem.</h2><p>See the six products and the shared foundation connecting them.</p><Link className="button button--white" href="/products">View all products <Arrow /></Link></section></article></div></main><SiteFooter /></>;
}
