import type { Metadata } from "next";
import { LegalDocument } from "@/components/legal-document";

export const metadata: Metadata = { title: "Privacy Policy", description: "NexisHub website privacy policy draft.", alternates: { canonical: "/legal/privacy" } };

export default function PrivacyPage() {
  return <LegalDocument title="Privacy Policy" summary="How the NexisHub company website handles information.">
    <h2>1. Scope</h2><p>This draft applies to the NexisHub company website. SiteNexis is a separate product experience with its own published privacy policy and service terms.</p>
    <h2>2. Information you provide</h2><p>If form delivery is enabled and you submit the contact or newsletter form, we process the information you enter, such as your name, email address, inquiry topic, and message. Submissions may be sent to the configured delivery endpoint so NexisHub can respond or manage the requested subscription.</p>
    <h2>3. Technical information</h2><p>The hosting platform may process standard request information needed to deliver and secure the website, including IP address, browser type, device information, requested URL, and timestamps. Optional analytics events are sent only after analytics consent. On public editorial and research pages, the site also contains a consent-gated Google AdSense loader; Google Privacy &amp; Messaging may present an applicable advertising consent message to visitors in covered regions.</p>
    <h2>4. How information is used</h2><p>Information is used to respond to inquiries, deliver requested updates, understand website performance, protect the service, and meet legal obligations. NexisHub does not use the company website to sell personal information.</p>
    <h2>5. Service providers</h2><p>The website is hosted on Vercel. When configured, contact and newsletter submissions are sent to a protected form-delivery endpoint, and consented analytics events are sent to a protected analytics endpoint. The repository does not hard-code a third-party analytics vendor. Google provides the AdSense advertising and Privacy &amp; Messaging services used on applicable public surfaces. Final provider disclosures, processor terms, and retention periods remain subject to operational confirmation and legal review.</p>
    <h2>6. Google advertising cookies</h2><p>When Google advertising is served, Google and its partners may use cookies or similar technologies to serve ads based on a user&apos;s visit to this website or other websites. Users can review or change Google&apos;s personalized advertising settings at <a href="https://adssettings.google.com/" rel="noreferrer">Google Ads Settings</a>. Users can also review available choices for some third-party advertising cookies at <a href="https://www.aboutads.info/choices/" rel="noreferrer">aboutads.info</a>. The Google Privacy &amp; Messaging message provides additional choices where it applies.</p>
    <h2>7. Retention and security</h2><p>Information should be kept only for as long as necessary for the stated purpose. Exact retention periods and the approved company security contact require legal and operational confirmation before launch.</p>
    <h2>8. Your choices</h2><p>You can choose “Essential only” or “Allow analytics” through the first-party website control. The first-party analytics choice is separate from any Google Privacy &amp; Messaging choice that applies to advertising in covered regions. Requests to access, correct, or delete submitted information can be made through the contact page once the official company contact destination is configured.</p>
    <h2>9. International and legal details</h2><p>The legal entity, governing jurisdiction, controller address, and any region-specific disclosures are pending company confirmation and legal review.</p>
    <h2>10. Changes</h2><p>Material changes will be reflected by updating the date at the top of this policy.</p>
  </LegalDocument>;
}
