import type { Metadata } from "next";
import Link from "next/link";
import { Arrow, SiteFooter, SiteHeader } from "@/components/site-chrome";

type Service = { slug: string; name: string; summary: string; deliverables: string[]; questions: { question: string; answer: string }[] };

const services: Service[] = [
  { slug: "discovery", name: "Product Discovery", summary: "Turn a difficult business problem into a clear product opportunity, a defined audience, and a buildable first release.", deliverables: ["Stakeholder and user interviews", "Problem statement and opportunity assessment", "Current workflow and competitor review", "Prioritised product scope and delivery roadmap", "Risks, assumptions, and decision record"], questions: [{ question: "How long does discovery take?", answer: "The duration depends on stakeholder access, research scope, and decision complexity. The engagement begins with a defined brief and ends with an agreed decision package." }, { question: "Do you build after discovery?", answer: "Yes, when the evidence supports it. Discovery can also end with a recommendation not to build or with a plan for another delivery partner." }] },
  { slug: "design", name: "Product Design", summary: "Create information architecture, user flows, interfaces, prototypes, and design systems that make complex products easier to use.", deliverables: ["Information architecture and user flows", "Wireframes and interactive prototypes", "Responsive interface design", "Design system foundations", "Accessibility review and design handoff"], questions: [{ question: "Can you work with an existing brand?", answer: "Yes. We can extend an existing identity or define a product interface system where the current brand does not meet the product needs." }, { question: "Do you validate designs?", answer: "Validation is planned around the users, risk, and access available. The method may include stakeholder review, prototype testing, or accessibility inspection." }] },
  { slug: "engineering", name: "Product Engineering", summary: "Build reliable web platforms, SaaS products, internal systems, APIs, and cloud infrastructure around the requirements that matter.", deliverables: ["Architecture and data model decisions", "Web application and API implementation", "Authentication, permissions, and operational controls", "Automated tests and deployment pipeline", "Documentation and handover"], questions: [{ question: "What technologies do you use?", answer: "The stack follows the product constraints. The Studio commonly works with Next.js, React, TypeScript, Node.js, Python, PostgreSQL, Supabase, REST APIs, and cloud infrastructure." }, { question: "Can you improve an existing product?", answer: "Yes. Existing products can begin with an architecture, performance, accessibility, security, or maintainability review." }] },
  { slug: "artificial-intelligence", name: "Artificial Intelligence", summary: "Apply agents, knowledge systems, semantic search, document intelligence, and workflow automation where they improve a real process.", deliverables: ["AI opportunity assessment and risk boundaries", "Knowledge and retrieval architecture", "Model and tool integration", "Evaluation set and human review plan", "Monitoring, permissions, and incident controls"], questions: [{ question: "Do you add AI to every project?", answer: "No. Deterministic software, search, or a normal workflow is preferred when it solves the problem more reliably." }, { question: "How do you control AI risk?", answer: "The work defines allowed actions, evidence sources, permissions, evaluation criteria, human checkpoints, logging, and rollback paths before production use." }] },
  { slug: "optimisation", name: "Product Optimisation", summary: "Improve existing software through architecture review, performance work, accessibility, security, testing, and AI visibility.", deliverables: ["Technical and product audit", "Performance and reliability improvements", "Accessibility and responsive corrections", "Security and privacy risk findings", "Prioritised improvement plan and verification"], questions: [{ question: "Can optimisation be a fixed-scope engagement?", answer: "Yes. A defined audit or improvement package can be scoped around a measurable outcome and acceptance criteria." }, { question: "Do you guarantee a specific performance score?", answer: "No. Results depend on the existing system, dependencies, content, and operating conditions. Targets and measurement conditions are documented before work begins." }] },
];

export function generateStaticParams() { return services.map(({ slug }) => ({ service: slug })); }

export async function generateMetadata({ params }: { params: Promise<{ service: string }> }): Promise<Metadata> {
  const { service: slug } = await params;
  const service = services.find((item) => item.slug === slug) ?? services[0];
  return { title: `${service.name} | NexisHub Studio`, description: service.summary, alternates: { canonical: `/studio/${service.slug}` } };
}

export default async function StudioServicePage({ params }: { params: Promise<{ service: string }> }) {
  const { service: slug } = await params;
  const service = services.find((item) => item.slug === slug) ?? services[0];
  const schema = { "@context": "https://schema.org", "@type": "Service", name: service.name, description: service.summary, provider: { "@type": "Organization", name: "NexisHub Studio", url: "https://nexishub.vercel.app/studio" }, areaServed: "Africa and international clients", url: `https://nexishub.vercel.app/studio/${service.slug}`, mainEntity: { "@type": "FAQPage", mainEntity: service.questions.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) } };
  return <><SiteHeader light /><main className="article-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} /><header className="article-hero"><div className="shell article-hero-inner"><nav className="article-breadcrumb" aria-label="Breadcrumb"><Link href="/">NexisHub</Link><span>/</span><Link href="/studio">Studio</Link><span>/</span><span>{service.name}</span></nav><p className="eyebrow"><span /> NexisHub Studio</p><h1>{service.name}<br /><em>with evidence behind the work.</em></h1><p className="article-deck">{service.summary}</p><div className="article-byline"><span>Engineering Intelligent Products.</span><span>Custom scope after discovery</span></div></div></header><div className="shell article-layout"><aside className="article-toc"><p>Studio services</p><nav aria-label="Studio services">{services.map((item) => <Link href={`/studio/${item.slug}`} key={item.slug}>{item.name}</Link>)}</nav></aside><article className="article-body"><p className="article-lead">The Studio shapes each engagement around the organisation, users, constraints, and desired outcome. The service is a working discipline, not a fixed technology package.</p><section><h2>What this includes</h2><ul className="article-checklist">{service.deliverables.map((item) => <li key={item}>{item}</li>)}</ul></section><section><h2>How the engagement works</h2><p>We begin by defining the problem and the decision the work must support. The scope, exclusions, dependencies, ownership, and acceptance criteria are recorded before implementation. Reviews happen at the points where a decision can still change without avoidable rework.</p><p>Where the work includes AI, the project also documents evidence sources, permissions, evaluation cases, human review, monitoring, and rollback conditions.</p></section><section><h2>Frequently asked questions</h2><div className="article-faq">{service.questions.map((item) => <details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</div></section><section className="article-product"><span>Start with the problem</span><h2>Tell us what needs to work better.</h2><p>Share the context, users, timeline, and constraints. We will determine whether a discovery sprint is the right next step.</p><Link className="button button--white" href="/studio">Discuss a Studio engagement <Arrow /></Link></section></article></div></main><SiteFooter /></>;
}
