import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { test } from "node:test";

const routes = ["src/app/page.tsx", "src/app/products/page.tsx", "src/app/products/sitenexis/page.tsx", "src/app/studio/page.tsx", "src/app/about/page.tsx", "src/app/blog/page.tsx", "src/app/blog/complete-guide-ai-software-development/page.tsx", "src/app/research/page.tsx", "src/app/contact/page.tsx", "src/app/legal/page.tsx", "src/app/legal/privacy/page.tsx", "src/app/legal/terms/page.tsx", "src/app/legal/cookies/page.tsx"];

test("all launch routes have page modules", () => { for (const route of routes) assert.ok(existsSync(route), `${route} is missing`); });
test("discovery endpoints are implemented", () => { for (const file of ["src/app/sitemap.ts", "src/app/robots.ts", "src/app/llms.txt/route.ts", "src/app/manifest.ts", "src/app/feed.xml/route.ts"]) assert.ok(existsSync(file), `${file} is missing`); });
test("SiteNexis links use the live application", () => { const links = readFileSync("src/lib/site-links.ts", "utf8"); assert.match(links, /https:\/\/sitenexis\.vercel\.app/); assert.doesNotMatch(links, /localhost/); });
test("approved product statuses and URLs are represented", () => { const products = readFileSync("src/lib/products.ts", "utf8").split("export const products")[1]; assert.equal((products.match(/status: "Live"/g) ?? []).length, 4); assert.equal((products.match(/status: "In development"/g) ?? []).length, 2); for (const url of ["https://teachnexis.vercel.app", "https://logicland.vercel.app", "https://eventnexis.vercel.app", "https://carebridge-io.vercel.app", "https://pnyx-psi.vercel.app"]) assert.match(products, new RegExp(url.replaceAll(".", "\\."))); });
test("legal drafts carry review status", () => { const legal = readFileSync("src/components/legal-document.tsx", "utf8"); assert.match(legal, /Draft for legal review/); });
test("published posts are integrated into discovery", () => { const posts = readFileSync("src/lib/posts.ts", "utf8"); const feed = readFileSync("src/app/feed.xml/route.ts", "utf8"); const sitemap = readFileSync("src/app/sitemap.ts", "utf8"); assert.match(posts, /complete-guide-ai-software-development/); assert.match(posts, /status: "Published"/); assert.match(feed, /blogPosts/); assert.match(sitemap, /blogPosts/); });
test("blog sections show five posts each", () => { const page = readFileSync("src/app/blog/page.tsx", "utf8"); const posts = readFileSync("src/lib/posts.ts", "utf8"); assert.equal((page.match(/posts: visibilityPosts\.slice/g) ?? []).length, 3); assert.equal((page.match(/posts: educationPosts\.slice/g) ?? []).length, 1); assert.match(page, /visibilityPosts\.slice\(0, 5\)/); assert.match(page, /visibilityPosts\.slice\(5, 10\)/); assert.match(page, /visibilityPosts\.slice\(10, 15\)/); assert.match(page, /educationPosts\.slice\(0, 5\)/); assert.match(page, /Education technology and TeachNexis/); assert.equal((posts.match(/educationPost\(\{/g) ?? []).length, 5); });
test("AI visibility cluster contains 15 complete linked guides", () => { const posts = readFileSync("src/lib/posts.ts", "utf8"); const content = readFileSync("src/lib/visibility-content.ts", "utf8"); const route = readFileSync("src/app/blog/[slug]/page.tsx", "utf8"); assert.equal((posts.match(/visibilityPost\(\{/g) ?? []).length, 15); assert.equal((posts.match(/siteNexisSource: "https:\/\/sitenexis\.vercel\.app\/blog\//g) ?? []).length, 15); for (const slug of posts.matchAll(/visibilityPost\(\{\s*\n\s*slug: "([^"]+)"/g)) assert.match(content, new RegExp(`slug: "${slug[1]}"`)); assert.match(route, /TechArticle/); assert.match(route, /FAQPage/); assert.match(route, /BreadcrumbList/); });
test("published guides use long-form deep dives", () => { const content = readFileSync("src/lib/visibility-content.ts", "utf8"); const route = readFileSync("src/app/blog/[slug]/page.tsx", "utf8"); assert.equal((content.match(/deepDive:/g) ?? []).length, 20); assert.match(route, /article-deep-dive/); });
test("AI visibility pages are statically generated and included in machine discovery", () => { const route = readFileSync("src/app/blog/[slug]/page.tsx", "utf8"); const image = readFileSync("src/app/blog/[slug]/opengraph-image.tsx", "utf8"); const llms = readFileSync("src/app/llms.txt/route.ts", "utf8"); assert.match(route, /generateStaticParams/); assert.match(route, /dynamicParams = false/); assert.match(image, /ImageResponse/); assert.match(llms, /visibilityPosts/); });
test("AI visibility pillar links to all fourteen supporting guides", () => { const posts = readFileSync("src/lib/posts.ts", "utf8"); const pillar = posts.split('slug: "complete-guide-ai-visibility"')[1].split("siteNexisSource:")[0]; assert.equal((pillar.match(/"[a-z0-9-]+"/g) ?? []).filter((value) => !value.includes("AI") && !value.includes("2026")).length >= 14, true); for (const slug of posts.matchAll(/visibilityPost\(\{\s*\n\s*slug: "([^"]+)"/g)) if (slug[1] !== "complete-guide-ai-visibility") assert.match(pillar, new RegExp(`"${slug[1]}"`)); });
