import type { VisibilityGuide } from "@/lib/visibility-content";

const googleAi = { label: "Google Search: optimizing for generative AI features", url: "https://developers.google.com/search/docs/fundamentals/ai-optimization-guide" };
const googleStructured = { label: "Google Search: structured data introduction", url: "https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data" };
const googleRobots = { label: "Google Search: robots.txt introduction", url: "https://developers.google.com/search/docs/crawling-indexing/robots/intro" };
const schema = { label: "Schema.org vocabulary", url: "https://schema.org/" };
const wcag = { label: "W3C Web Content Accessibility Guidelines", url: "https://www.w3.org/TR/WCAG22/" };

type GuideSeed = {
  slug: string;
  lead: string;
  title: string;
  topic: string;
  audience: string;
  focus: string;
  related: string[];
  references: { label: string; url: string }[];
};

const seeds: readonly GuideSeed[] = [
  { slug: "how-ai-systems-discover-websites", title: "How AI Systems Discover and Interpret Websites", lead: "AI-assisted discovery depends on a chain of access, interpretation, retrieval, evidence, and representation. Understanding that chain makes website decisions more precise.", topic: "AI systems discover websites through several separate operations rather than one universal crawler or ranking process.", audience: "technical and content teams responsible for a public website", focus: "access, identity, extraction, retrieval, and representation", related: ["complete-guide-ai-visibility", "rag-search-content-discovery", "technical-ai-crawlability-checklist"], references: [googleAi, googleRobots] },
  { slug: "what-makes-website-citable-by-ai", title: "What Makes a Website Citable by an AI System?", lead: "Citation readiness begins with a claim that can be located, understood, attributed, and checked. It cannot be created by markup or repetition alone.", topic: "A citable page gives a retrieval system a specific claim, enough surrounding context, and evidence that a reader can inspect.", audience: "publishers, researchers, product teams, and subject-matter experts", focus: "specific claims, provenance, authorship, freshness, and limitations", related: ["complete-guide-ai-visibility", "create-citation-ready-content", "measure-ai-visibility"], references: [googleAi, schema] },
  { slug: "structured-data-for-machine-understanding", title: "Structured Data for Machine Understanding", lead: "Structured data is most useful when it accurately describes visible content, stable entities, and real relationships that people can verify on the page.", topic: "Structured data provides a machine-readable layer, but it works only when the markup and visible page agree.", audience: "web engineers, SEO practitioners, and product teams", focus: "entity types, visible-content parity, validation, and maintenance", related: ["structured-data-ai-machine-trust", "entity-clarity-ai-systems", "ai-readable-website-architecture"], references: [googleStructured, schema] },
  { slug: "why-traditional-seo-does-not-explain-ai-visibility", title: "Why Traditional SEO Does Not Fully Explain AI Visibility", lead: "Search optimization remains part of the foundation, but ranked documents, retrieved passages, generated answers, and citations are different observations.", topic: "The useful question is not whether SEO has ended. It is which parts of discovery are shared and which require separate measurement.", audience: "marketing leaders, engineers, editors, and analysts", focus: "shared foundations, different outputs, and measurement boundaries", related: ["ai-visibility-vs-traditional-seo", "measure-ai-visibility", "practical-geo-strategy"], references: [googleAi] },
  { slug: "retrieval-ranking-recommendation-ai-search", title: "Retrieval, Ranking, and Recommendation: How AI Search Differs", lead: "AI search can combine retrieval, ranking, synthesis, and recommendation. Treating those steps as one score makes diagnosis and accountability harder.", topic: "A useful model separates finding candidate sources from selecting, composing, and presenting an answer.", audience: "AI product teams, web engineers, and researchers", focus: "candidate retrieval, selection, synthesis, citation, and user action", related: ["rag-search-content-discovery", "how-ai-platforms-discover-sources", "measure-ai-visibility"], references: [googleAi] },
  { slug: "audit-framework-ai-readable-websites", title: "A Practical Audit Framework for AI-Readable Websites", lead: "A responsible audit identifies the failing layer, records evidence, assigns an owner, and distinguishes technical observations from modeled estimates.", topic: "An AI-readable website audit should be a repeatable engineering and editorial process rather than a mysterious score.", audience: "website owners and teams beginning an AI visibility programme", focus: "baseline, access, meaning, evidence, measurement, and review", related: ["complete-guide-ai-visibility", "technical-ai-crawlability-checklist", "90-day-ai-visibility-roadmap"], references: [googleAi, googleRobots, wcag] },
  { slug: "machine-trust-without-measuring-truth", title: "Measuring Machine Trust Without Pretending to Measure Truth", lead: "Machine trust metrics can describe consistency, evidence, and representation. They cannot turn a proxy into truth or remove the need for human judgment.", topic: "Trust measurement becomes useful when its construct, inputs, uncertainty, and misuse limits are explicit.", audience: "researchers, AI product teams, and decision-makers", focus: "construct definition, proxy limits, uncertainty, and governance", related: ["structured-data-ai-machine-trust", "measure-ai-visibility", "complete-guide-ai-visibility"], references: [schema, googleAi] },
  { slug: "evidence-first-content-human-machine-readers", title: "Building Evidence-First Content for Human and Machine Readers", lead: "Evidence-first writing makes claims easier for people to evaluate and easier for retrieval systems to represent without losing their limits.", topic: "The strongest content begins with a claim inventory and assigns a source, owner, date, and confidence boundary to important statements.", audience: "technical writers, researchers, founders, and editorial teams", focus: "claim design, source quality, uncertainty, authorship, and correction", related: ["create-citation-ready-content", "content-structure-ai-retrieval", "complete-guide-ai-visibility"], references: [googleAi, schema] },
  { slug: "technical-anatomy-machine-discoverable-website", title: "The Technical Anatomy of a Machine-Discoverable Website", lead: "Machine discoverability is built from ordinary web engineering: stable responses, accessible content, clear identity, useful links, metadata, and maintainable delivery.", topic: "A discoverable website exposes its important content through a reliable technical path from request to readable document.", audience: "frontend engineers, platform teams, and technical website owners", focus: "HTTP behavior, rendering, navigation, canonicals, sitemaps, metadata, and accessibility", related: ["technical-ai-crawlability-checklist", "ai-readable-website-architecture", "structured-data-ai-machine-trust"], references: [googleRobots, googleStructured, wcag] },
  { slug: "entity-clarity-missing-layer-ai-search", title: "Entity Clarity: The Missing Layer in AI Search", lead: "Entity clarity helps systems resolve who an organisation is, what it offers, which people are responsible, and how related pages fit together.", topic: "A clear entity is not a slogan. It is a consistent, evidence-backed identity expressed across content, metadata, links, and authoritative references.", audience: "companies, institutions, product teams, and editorial owners", focus: "names, definitions, relationships, authorship, and corroboration", related: ["entity-clarity-ai-systems", "structured-data-ai-machine-trust", "how-ai-platforms-discover-sources"], references: [schema, googleStructured] },
];

const point = (title: string, detail: string) => ({ title, detail });

export const additionalVisibilityGuides: readonly VisibilityGuide[] = seeds.map((seed) => ({
  slug: seed.slug,
  lead: seed.lead,
  overview: [
    `${seed.topic} The distinction matters because different failures require different owners and different evidence. A page that cannot be reached needs engineering work. A page that can be reached but cannot be interpreted needs information architecture or editorial work. A page that is retrieved but represented inaccurately needs stronger definitions, evidence, or review.`,
    `This guide is written for ${seed.audience}. It treats ${seed.focus} as connected concerns, while keeping their measurements separate. The objective is not to control an external answer engine. The objective is to make useful information accessible, understandable, defensible, and easier to maintain.`,
  ],
  deepDive: [
    { title: "Start with the unit being observed", paragraphs: [`Before changing a page, define what is being measured. The observation may be a successful response, a rendered section, a retrieved passage, a citation, a description of an organisation, or a user action after discovery. These are related events, not interchangeable outcomes.`, `Record the question, page, date, environment, evidence, and uncertainty. This gives a future reviewer enough context to understand what changed and prevents a volatile answer from becoming an unsupported permanent claim.`] },
    { title: "Make the important meaning local", paragraphs: [`A retrieved section may be separated from the rest of its page. Important sections should therefore identify their subject, scope, intended audience, and relevant qualification near the claim. This does not require repetitive writing. It requires deliberate context and headings that describe the question being answered.`, `Visible content remains the source of truth. Metadata, navigation labels, structured data, and linked references should reinforce the page rather than introduce a second version of its identity.`] },
    { title: "Assign an owner and a review date", paragraphs: [`Discovery quality decays when nobody owns the page after publication. Assign responsibility for technical access, factual accuracy, source freshness, and correction handling. The review interval should reflect the subject. A historical definition and a current product specification do not need the same schedule.`, `A small change record is often enough: the problem, intervention, expected mechanism, date, evidence to inspect, and decision after review. This creates a practical bridge between publishing and research discipline.`] },
    { title: "Turn the framework into a working review", paragraphs: [`For ${seed.title.toLowerCase()}, a useful review should produce decisions rather than observations alone. Start by selecting a small set of representative pages or questions. Record what a person can see, what a crawler can access, what a retrieval system might extract, and what a reader would need to verify. When the evidence is incomplete, record the gap instead of filling it with a confident assumption.`, `The review should then rank work by consequence and reversibility. A broken canonical, inaccessible content, or contradictory organisation name usually deserves attention before a cosmetic rewrite. A change that affects many pages should have a clear owner, a rollback path, and a later review date. A narrow experiment should be labelled as an experiment and should not be presented as a universal rule.`, `This discipline also protects the editorial team from false precision. Some outputs can be checked directly, such as status codes, visible headings, links, or published dates. Other outputs require sampling, such as whether an answer system retrieves a source or represents it accurately. The report should name the difference so that a reader can understand what the evidence supports.`] },
    { title: "Use the page as part of a larger knowledge system", paragraphs: [`No article carries all of its meaning alone. A strong page has a clear relationship to a hub, a definition, a method, a product explanation, or a source record. Those relationships should be visible in the page itself and should make sense to a person following them. Internal links are most useful when they answer the next reasonable question, not when they exist only to distribute authority.`, `For this topic, the related pages listed at the end of the article are deliberate continuation points. The pillar explains the wider field. The supporting guides narrow the question. The research programme records the boundary between a working framework and validated findings. The product link, where present, explains an application without turning the article into a product claim.`, `This structure makes the content easier to maintain. If a definition changes, the team can identify the pages that depend on it. If a source is withdrawn or superseded, the reference can be reviewed without treating the entire archive as disposable. A useful knowledge system is not merely large. It is legible, connected, and capable of correction.`] },
    { title: "A publication standard that survives review", paragraphs: [`Before publication, read the article as a practitioner who has not followed the earlier series. The opening should state the problem and the boundaries. The main sections should explain the mechanism in plain language before introducing specialised terms. Examples should be labelled as examples, observations should identify their source, and recommendations should explain the condition under which they apply.`, `Then review the page as an editor and an engineer. The editor checks whether every material claim is supported, current, attributable, and appropriately qualified. The engineer checks response behaviour, rendering, headings, links, canonical identity, metadata, structured data, accessibility, and print output. Neither review replaces the other. A technically perfect page can still make an unsupported claim, and a carefully sourced page can still be impossible to reach.`, `Finally, record what would change the conclusion. This question is not a formality. It identifies assumptions that deserve testing and makes the article more useful to people who disagree with it. A durable publication does not try to sound certain about every part of a changing system. It shows readers which parts are known, which are inferred, and which remain open.`] },
  ],
  principles: [
    point("Define the construct", `State exactly what ${seed.focus} means in this article and what it does not measure.`),
    point("Keep evidence visible", "Attach sources, dates, authorship, examples, or observations to claims that depend on them."),
    point("Design for extraction", "Use headings, local context, and stable sections that remain understandable outside the full page."),
    point("Separate outputs", "Do not combine access, retrieval, citation, representation, and business outcomes into one unexplained score."),
    point("Plan maintenance", "Record owners, review dates, corrections, and the evidence needed for future updates."),
  ],
  workflow: [
    point("Set the baseline", "List priority pages, questions, entities, sources, and observed outputs before making changes."),
    point("Repair access", "Check responses, rendering, links, robots controls, canonicals, sitemaps, and accessibility."),
    point("Clarify the page", "Give the page one purpose, define important terms, and keep related claims close to their evidence."),
    point("Strengthen relationships", "Link to genuinely related pages using descriptive anchors and consistent entity names."),
    point("Review the result", "Repeat the observation, preserve the evidence, document uncertainty, and decide what should change next."),
  ],
  pitfalls: [
    point("Treating a proxy as truth", "A diagnostic score or observed citation can inform a decision, but it cannot prove factual truth or causal impact."),
    point("Publishing markup without parity", "Structured data that contradicts visible content creates ambiguity and maintenance risk."),
    point("Scaling before learning", "Publishing many pages before the first cluster has a clear purpose can create duplication and conflicting claims."),
  ],
  measurement: ["Report technical access, content clarity, observed retrieval or citation evidence, representation accuracy, and business outcomes as separate evidence classes.", "For every measurement, record the date, sample, method, limitations, and the decision the result is intended to support. Do not use a modeled readiness score as proof of external selection."],
  future: "The interfaces used for discovery will change, but durable practice will remain recognisable: accessible documents, explicit meaning, coherent relationships, inspectable evidence, and accountable maintenance.",
  takeaways: ["Define the observation before choosing the metric.", "Repair access before adding volume.", "Make important claims locally understandable.", "Keep evidence and interpretation separate.", "Treat maintenance as part of publishing."],
  faq: [
    { question: "Does this approach guarantee AI visibility or citation?", answer: "No. External systems select and represent sources under conditions the publisher does not control. The framework improves clarity and evidence without promising selection." },
    { question: "Should every page contain structured data?", answer: "No. Use only accurate types that describe visible, relevant content and can be maintained." },
    { question: "What should a small team do first?", answer: "Choose a small set of important pages, establish a baseline, repair technical access, clarify definitions, and document the evidence for each change." },
  ],
  references: seed.references,
}));
