export type ResearchStatus = "Concept" | "Planning" | "Planned" | "Methodology" | "Pilot" | "Active Research" | "Peer Review" | "Revision" | "Published" | "Archived";
export type ResearchProgramme = { slug: string; title: string; status: ResearchStatus; area: string; overview: string; motivation: string; questions: string[]; deliverables: string[]; relatedProducts: string[] };

const programme = (title: string, area: string, overview: string, motivation: string, questions: string[], deliverables: string[], relatedProducts: string[] = []) => ({ slug: title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""), title, status: "Planned" as const, area, overview, motivation, questions, deliverables, relatedProducts });

export const nriProgrammes: readonly ResearchProgramme[] = [
  programme("AI Visibility Index", "AI Visibility", "A framework for measuring machine discovery, retrieval, representation, and attribution.", "Public information is increasingly encountered through AI-assisted systems, but visibility is often discussed without separating observation from inference.", ["Which source conditions are associated with retrieval?", "How stable are observations across systems and dates?"], ["Framework paper", "Annotation guide", "Pilot dataset", "Stability report"], ["SiteNexis"]),
  programme("Citation Intelligence Framework", "Information Retrieval", "A framework for studying when, how, and why information systems attribute sources.", "Attribution can support trust, but citation presence alone does not establish accuracy or usefulness.", ["What forms of attribution are observable?", "How can citation quality be assessed separately from citation presence?"], ["Taxonomy", "Annotation guide", "Benchmark protocol"]),
  programme("Machine Trust Score", "Knowledge Systems", "A proposed set of measures for examining evidence, identity, provenance, and source reliability signals.", "Machines require structured evidence to distinguish a source from an unsupported claim.", ["Which trust signals are observable?", "Can reviewers classify provenance consistently?"], ["Measurement framework", "Reviewer calibration", "Technical report"]),
  programme("Future of AI Search", "Search Intelligence", "A state of industry study of retrieval, synthesis, attribution, and user control in AI-assisted search.", "Search interfaces are changing faster than established measurement practices.", ["How are discovery tasks changing?", "Which controls improve user understanding?"], ["Literature review", "Industry report", "Research roadmap"]),
  programme("Measuring Trust in Large Language Models", "AI Evaluation", "An investigation of how users and systems can assess confidence, evidence, uncertainty, and correction.", "Fluent output can be mistaken for reliable output when uncertainty is hidden.", ["Which trust measures predict appropriate reliance?", "How should abstention be evaluated?"], ["Evaluation framework", "User study protocol"]),
  programme("Autonomous AI Agents in Enterprise", "AI Agents", "A study of permissions, observability, evaluation, and human control for enterprise agents.", "Enterprise automation creates operational value and new failure modes at the same time.", ["Which tasks justify agentic autonomy?", "What controls reduce consequential errors?"], ["Risk framework", "Evaluation suite", "Engineering report"]),
  programme("Human-AI Collaboration Framework", "Human-Computer Interaction", "A framework for designing useful divisions of labour between people and intelligent systems.", "The best system is not always the most autonomous system.", ["Where should responsibility remain human?", "How should handoffs be designed?"], ["Design framework", "Interaction patterns"]),
  programme("AI for Mathematics Education", "Education Technology", "Research on AI tools that support mathematical reasoning, practice, feedback, and teacher judgement.", "Mathematics learning requires reasoning and misconception diagnosis, not only answer generation.", ["Which interventions improve reasoning?", "How can teachers inspect model feedback?"], ["Literature review", "Classroom protocol"]),
  programme("AI Tutors versus Traditional Learning Models", "Learning Science", "A comparative study of AI tutoring workflows and established teaching models.", "New tools should be compared against credible alternatives rather than impressive demonstrations.", ["Which outcomes differ?", "For whom and under what conditions?"], ["Comparison framework", "Evidence review"]),
  programme("Responsible AI in African Education", "Education Policy", "A study of access, language, privacy, teacher agency, and accountability in African education systems.", "Educational AI must reflect local conditions, not only imported assumptions.", ["What readiness conditions matter?", "Which risks are context dependent?"], ["Policy report", "Readiness framework"]),
  programme("Digital Health Readiness Index", "Healthcare Informatics", "A framework for assessing whether health organisations can safely adopt digital and AI systems.", "Readiness includes governance, infrastructure, workforce, interoperability, and patient protection.", ["Which readiness dimensions are measurable?", "How should gaps be prioritised?"], ["Index framework", "Assessment protocol"], ["CareBridge"]),
  programme("AI in Primary Healthcare Systems", "Digital Health", "Research on safe decision support, records, triage, and workflow assistance in primary care.", "Primary care systems need useful tools that preserve clinical responsibility and patient dignity.", ["Which workflows benefit?", "What evidence and oversight are required?"], ["Evidence review", "Safety framework"]),
  programme("Sustainable SaaS Architecture", "Software Architecture", "A study of architecture choices that improve operational sustainability, cost awareness, and maintainability.", "Long-lived software requires more than an initial successful launch.", ["Which practices reduce waste?", "How should sustainability be measured?"], ["Engineering framework", "Reference architecture"]),
  programme("Engineering Products for Long-Term Maintainability", "Product Engineering", "Research on the technical and organisational conditions that keep products understandable and changeable.", "Maintenance burden is a product outcome, not only an engineering concern.", ["Which decisions predict maintainability?", "How can teams measure change friction?"], ["Maintainability framework", "Playbook"]),
  programme("Software Systems that Outlive Their Founders", "Software Architecture", "A study of documentation, governance, ownership, and architecture for institutional continuity.", "Products should not depend on one person retaining invisible context.", ["What enables continuity?", "How should knowledge transfer be documented?"], ["Governance framework", "Case study protocol"]),
  programme("Future of Multi-Agent Collaboration", "Multi-Agent Systems", "Research on coordination, delegation, communication, and evaluation among multiple AI agents.", "More agents create more coordination surfaces and more opportunities for hidden failure.", ["When does multi-agent design help?", "How should coordination be evaluated?"], ["Taxonomy", "Benchmark protocol"]),
  programme("Enterprise Knowledge Graph Architecture", "Knowledge Systems", "A reference architecture for durable enterprise entities, relationships, provenance, and access control.", "Organisational knowledge is difficult to retrieve when relationships and ownership are implicit.", ["Which graph structures support useful retrieval?", "How should provenance be maintained?"], ["Reference architecture", "Implementation guide"]),
  programme("Semantic Infrastructure for AI Search", "Search Intelligence", "Research on the content, metadata, and relationship infrastructure required for reliable machine discovery.", "Search quality depends on source structure as well as model behaviour.", ["Which semantic signals are durable?", "How can source owners inspect them?"], ["Technical report", "Audit protocol"], ["SiteNexis"]),
  programme("Benchmarking Large Language Models for Engineering Tasks", "AI Evaluation", "A benchmark design for testing language models on realistic software engineering tasks.", "Engineering benchmarks should reflect maintenance, debugging, security, and trade-offs rather than only code generation.", ["Which tasks are representative?", "How should human review be incorporated?"], ["Benchmark dataset", "Evaluation harness"]),
  programme("Context Engineering versus Prompt Engineering", "LLM Engineering", "A study of context selection, memory, tools, and instruction design in model-based systems.", "System behaviour depends on the whole information environment, not only the prompt.", ["Which context practices improve outcomes?", "How should context cost and quality be measured?"], ["Framework paper", "Engineering guide"]),
  programme("Evaluation Frameworks for AI Agents", "AI Evaluation", "A framework for evaluating agent task success, tool use, safety, cost, latency, and recovery.", "Agent evaluation must cover process and consequences, not only final text.", ["Which dimensions are essential?", "How should agent failures be reproduced?"], ["Evaluation framework", "Reference implementation"]),
  programme("Measuring Software Intelligence", "Software Engineering", "A research programme on measurable system capabilities, decision support, and engineering effectiveness.", "Intelligence claims need operational definitions and observable evidence.", ["What does software intelligence mean?", "Which measures predict useful outcomes?"], ["Position paper", "Measurement taxonomy"]),
  programme("Human-Centred Artificial Intelligence", "Human-Computer Interaction", "Research on systems that make people more capable while preserving agency, dignity, and understanding.", "Human-centred design must account for system behaviour, not only interface appearance.", ["How should agency be evaluated?", "What makes oversight meaningful?"], ["Design framework", "Evaluation guide"]),
  programme("Building Explainable AI Systems", "AI Safety", "A study of explanations, evidence, uncertainty, and user understanding in AI products.", "An explanation is useful only if it improves understanding or decision quality.", ["Which explanations help?", "How should explanation quality be tested?"], ["Framework paper", "User research protocol"]),
  programme("The Future of Digital Identity", "Digital Infrastructure", "Research on identity, consent, access, privacy, and trust in digital services.", "Digital identity systems affect participation, safety, and control over personal information.", ["Which identity models preserve user control?", "How should interoperability be governed?"], ["Policy paper", "Architecture framework"]),
  programme("African AI Readiness Index", "Technology Policy", "A framework for assessing institutional, infrastructure, skills, governance, and adoption readiness across African contexts.", "AI readiness is broader than model access and should reflect local capability.", ["Which readiness indicators are defensible?", "How should country differences be represented?"], ["Index framework", "Annual report"]),
  programme("AI and Digital Sovereignty", "Technology Policy", "Research on infrastructure, data, models, procurement, skills, and governance choices that shape digital autonomy.", "Digital dependence creates strategic choices that require evidence rather than slogans.", ["Which dependencies matter?", "What policy options are practical?"], ["Policy report", "Decision framework"]),
  programme("Intelligent Government Platforms", "Government Technology", "Research on trustworthy digital public services, workflow automation, and citizen-facing information systems.", "Public systems require stronger accountability, accessibility, and continuity than ordinary products.", ["Which platforms improve service access?", "How should public AI be governed?"], ["Architecture guide", "Policy recommendations"]),
  programme("Future of Product Engineering", "Product Engineering", "A study of how research, design, engineering, operations, and governance combine in modern product teams.", "Product engineering is evolving as software becomes more intelligent and operationally complex.", ["Which team practices improve outcomes?", "How should quality be measured?"], ["Industry report", "Engineering playbook"]),
  programme("Autonomous Enterprises", "Innovation Economics", "Research on organisations that combine software automation, human responsibility, and adaptive decision systems.", "Automation changes organisational design as well as individual workflows.", ["What should autonomy mean at organisational scale?", "Which governance mechanisms are required?"], ["Position paper", "Research roadmap"]),
];

export const nriProgrammeBySlug = new Map(nriProgrammes.map((item) => [item.slug, item]));
