import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";

export const metadata: Metadata = {
  title: "AI Visibility Index: Research Framework",
  description: "Nexis Research Institute working paper on machine discovery, retrieval, representation, and attribution.",
  alternates: { canonical: "/research/ai-visibility-index" },
};

export default function AiVisibilityIndexPaper() {
  return <><SiteHeader light /><main className="article-page"><header className="article-hero"><div className="shell article-hero-inner">
    <nav className="article-breadcrumb" aria-label="Breadcrumb"><Link href="/">NexisHub</Link><span>/</span><Link href="/research">Research</Link><span>/</span><span>Working paper</span></nav>
    <p className="eyebrow"><span /> NRI Working Paper 001 · Version 0.1</p>
    <h1>AI Visibility Index:<br /><em>A framework for measuring machine discovery.</em></h1>
    <p className="article-deck">A proposed framework for studying how public information is discovered, retrieved, represented, and attributed by AI-assisted systems.</p>
    <div className="article-byline"><span>By Nexis Research Institute</span><span>Published <time dateTime="2026-07-27">July 27, 2026</time></span><span>Status: pre-review working paper</span></div>
  </div></header><div className="shell article-layout"><aside className="article-toc"><p>In this paper</p><nav aria-label="Table of contents"><a href="#abstract">Abstract</a><a href="#questions">Research questions</a><a href="#method">Methodology</a><a href="#measurement">Measurement</a><a href="#limits">Ethics and limits</a><a href="#review">Review gate</a></nav></aside><article className="article-body">
    <p className="article-lead">This paper proposes a transparent framework for studying AI visibility. It does not present a validated index, rank organisations, predict citation probability, or guarantee commercial performance.</p>
    <section id="abstract"><h2>Abstract</h2><p>AI-assisted information systems are becoming an important route through which people discover organisations, products, services, and public information. Existing discussions often combine technical accessibility, search performance, generated answers, citations, and business outcomes into one broad idea of visibility. That combination makes it difficult to identify what was observed, what was inferred, and what remains unknown.</p><p>The AI Visibility Index is proposed as a multi-dimensional research framework. It separates source access, identity, information architecture, semantic clarity, evidence, retrieval presence, representation accuracy, attribution, and maintenance. The framework is designed for reproducible observation rather than optimisation folklore. It requires declared test conditions, independent review, uncertainty reporting, and explicit separation between diagnostic measures and outcomes.</p><p>Version 0.1 defines the research questions, pilot methodology, data requirements, review process, and conditions under which the framework should be revised or abandoned. Empirical validation is a future phase. No organisation-level result is claimed in this publication.</p><p><strong>Keywords:</strong> AI visibility, information retrieval, machine discovery, source attribution, entity clarity, evaluation, reproducibility.</p></section>
    <section id="questions"><h2>Research questions and objectives</h2><p>The central question is whether a transparent set of technical, semantic, retrieval, evidence, and representation measures can describe meaningful differences in how organisations are discovered and represented in AI-assisted information tasks.</p><ol><li>Which observable website conditions are associated with successful source retrieval?</li><li>Which conditions are associated with accurate organisation and product representation?</li><li>How stable are observations across systems, prompts, dates, locations, and interaction modes?</li><li>Which measures are direct observations and which are diagnostic proxies?</li><li>Can independent reviewers apply the classifications consistently?</li><li>Which changes make a source clearer without encouraging manipulation?</li></ol><p>The first objective is definition. The second is reproducibility. The third is usefulness to engineers and information owners. A composite score will not be created unless evidence shows that aggregation is interpretable, stable, and less misleading than reporting dimensions separately.</p></section>
    <section id="method"><h2>Methodology</h2><h3>Framework specification</h3><p>Before outcome testing, the research team will define dimensions, labels, units of analysis, exclusions, query intents, collection limits, and planned analyses. Changes will be recorded in a revision log.</p><h3>Declared sample</h3><p>The pilot will use a controlled sample across software and technology, education, healthcare, professional services, nonprofit and community organisations, and public or civic information. Sector, region, size category, language, platform conditions, and selection source will be recorded. A convenience sample will not be described as representative.</p><h3>Source audit</h3><p>Researchers will collect public observations about response status, canonical identity, robots controls, rendered content, headings, navigation, entity definitions, structured data, authorship, dates, sources, and internal relationships. Tool version, crawl date, request limits, and exclusions will be recorded.</p><h3>Fixed discovery tests</h3><p>Each source will be evaluated against a declared set of information tasks. The record will include the exact prompt or query, system, mode, date, location where relevant, result, selected source, attribution behaviour, and representation assessment. Exploratory observations will remain separate from the fixed test set.</p><h3>Independent review and replication</h3><p>At least two reviewers will classify a defined subset. They will record evidence locations, confidence, uncertainty, and conflicts of interest. Disagreements will be preserved and adjudicated by the research lead. The final report will publish the method, sample logic, version information, de-identified records where permitted, and reproduction instructions.</p></section>
    <section id="measurement"><h2>Measurement framework</h2><p>Version 0.1 proposes these dimensions for testing. They are not validated weights or a final score:</p><ul className="article-checklist"><li><strong>Access and crawlability:</strong> whether the public source can be reached and processed under declared conditions.</li><li><strong>Canonical identity:</strong> whether the organisation, domain, products, and official relationships are distinguishable.</li><li><strong>Information architecture:</strong> whether important information has stable and coherent locations.</li><li><strong>Semantic clarity:</strong> whether sections, claims, labels, and terminology communicate consistent meaning.</li><li><strong>Evidence and provenance:</strong> whether important claims identify authorship, dates, sources, or supporting context.</li><li><strong>Freshness and maintenance:</strong> whether time-sensitive information is dated and maintained.</li><li><strong>Retrieval presence:</strong> whether relevant source material appears in a declared test.</li><li><strong>Representation accuracy:</strong> whether an observed description matches documented facts and limitations.</li><li><strong>Attribution:</strong> whether an interface identifies or links the source when attribution is available.</li></ul><p>Results should first be reported as distributions, examples, missingness, and uncertainty. Any later aggregation must show the effect of alternative scoring choices and must not imply causation.</p></section>
    <section id="limits"><h2>Ethics, privacy, and threats to validity</h2><p>The pilot is limited to public information unless a separate agreement establishes another basis. Researchers will not request passwords or private content. Organisation names, screenshots, quotations, metrics, and organisation-level results require the publication permission specified in the participation materials.</p><p>AI systems change over time. Providers expose different modes. Prompts, locations, languages, and dates affect observations. Public pages do not reveal every retrieval process. Reviewers may interpret clarity and accuracy differently. A score may encourage gaming if its construction is simplified.</p><p>The research team must distinguish evidence from interpretation, disclose relationships with sampled organisations, minimise collected data, retain records for a declared period, and provide a correction process for factual errors. Product or commercial interests must not determine the result.</p></section>
    <section id="review"><h2>Review gate and planned outputs</h2><p>This working paper is intended to produce a public annotation guide, a reproducible audit protocol, a small documented benchmark dataset, a technical report on cross-system stability, and a revision log. The first empirical report will be published only after the pilot is complete and the research lead confirms that the evidence supports the stated claims.</p><p>Before that report, the paper should receive technical review, methodology review, and ethics or privacy review where required. Reviewers should be named in the publication record. A publication date is not evidence of peer review.</p><h3>What would change our mind?</h3><p>We would revise or abandon the framework if independent reviewers cannot apply its definitions consistently, if repeated tests are too unstable for the intended use, if the dimensions do not distinguish meaningful conditions, or if the framework creates stronger incentives for signal manipulation than for useful public information.</p><div className="article-callout"><strong>Publication status</strong><p>Working paper 001. Pre-review. No validated index score, organisation ranking, or empirical finding is claimed.</p></div></section>
    <section className="article-references"><h2>Supporting standards</h2><ol><li><a href="https://www.nist.gov/itl/ai-risk-management-framework">NIST AI Risk Management Framework</a></li><li><a href="https://www.w3.org/TR/">World Wide Web Consortium standards</a></li><li><a href="https://owasp.org/www-project-top-ten/">OWASP Top Ten</a></li></ol></section>
  </article></div></main><SiteFooter /></>;
}
