import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { EditorialExplorer } from "@/components/editorial-explorer";
import { Arrow, SiteFooter, SiteHeader } from "@/components/site-chrome";
import { NewsletterForm } from "@/components/newsletter-form";
import { siteNexisLinks } from "@/lib/site-links";
import { blogPosts, educationPosts, featuredVisibilityPost, visibilityPosts } from "@/lib/posts";

export const metadata: Metadata = { title: "Blog", description: "NexisHub writing on AI development, machine visibility, modern web engineering, infrastructure, and human-first software.", alternates: { canonical: "/blog", types: { "application/rss+xml": "/feed.xml" } } };

const blogSections = [
  { title: "AI visibility foundations", description: "Start with the concepts that separate machine discovery from traditional search.", posts: visibilityPosts.slice(0, 5) },
  { title: "Retrieval, entities, and trust", description: "Strengthen the page-level signals that help AI systems extract, understand, and cite content.", posts: visibilityPosts.slice(5, 10) },
  { title: "Measurement and operating rhythm", description: "Turn AI visibility into a repeatable program with source discovery, metrics, and a practical roadmap.", posts: visibilityPosts.slice(10, 15) },
  { title: "Education technology and TeachNexis", description: "Five practical guides for schools, teachers, lesson planning, classroom workflows, and student analytics.", posts: educationPosts.slice(0, 5) },
] as const;

export default function BlogPage() {
  return <><SiteHeader /><main className="blog-page"><section className="blog-hero"><div className="blog-orb" aria-hidden="true" /><div className="shell blog-hero-inner"><div><p className="eyebrow"><span /> NexisHub knowledge platform</p><h1>Ideas for the<br /><em>machine-first future.</em></h1><p>Research, engineering notes, guides, and clear thinking about intelligent software, written to educate first and promote only when genuinely useful.</p><div className="blog-actions"><a className="button" href="#latest">Explore the guides <Arrow /></a><Link className="button button--ghost" href="/research">Research agenda</Link></div></div><aside className="blog-feature"><span>Now publishing</span><strong>{blogPosts.length} reviewed field guides.</strong><p>Practical, sourced guidance on AI software, machine discovery, retrieval, evidence, and responsible measurement.</p><div><small>First principles</small><b>Evidence · Clarity · Craft</b></div></aside></div></section>
      <section className="blog-latest" id="latest"><div className="shell"><div className="blog-latest-heading"><p className="kicker">E1 · New pillar guide</p><span>Published July 23, 2026 · {featuredVisibilityPost.readingTime}</span></div><Link href={featuredVisibilityPost.canonicalPath} className="blog-latest-card"><div><span>{featuredVisibilityPost.category}</span><h2>{featuredVisibilityPost.title}</h2><p>{featuredVisibilityPost.description}</p><b>Read the complete guide <Arrow /></b></div><Image src={featuredVisibilityPost.featuredImage} alt={featuredVisibilityPost.featuredImageAlt} width={1200} height={630} unoptimized /></Link></div></section>
      <section className="blog-library"><div className="shell"><div className="blog-section-title"><div><p className="kicker">Published sections</p><h2>Five guides per section.</h2></div><p>Each section groups five reviewed field guides around a practical AI visibility workflow.</p></div>{blogSections.map((section) => <div className="blog-post-section" key={section.title} data-blog-section={section.title}><div className="blog-post-section-heading"><h3>{section.title}</h3><p>{section.description}</p></div><div className="blog-library-grid">{section.posts.map((post) => <article key={post.slug}><span>{post.cluster} · {post.category}</span><h3><Link href={post.canonicalPath}>{post.title}</Link></h3><p>{post.description}</p><div><small>{post.readingTime}</small><Link href={post.canonicalPath} aria-label={`Read ${post.title}`}><Arrow /></Link></div></article>)}</div></div>)}</div></section>
      <section className="blog-intro"><div className="shell blog-intro-grid"><p className="kicker">A knowledge platform, not a content treadmill</p><div><h2>Useful enough to save.<br /><span>Clear enough to trust.</span></h2><p>NexisHub publishing will connect practical engineering, applied research, and the decisions behind its products. Every article should have a reason to exist beyond filling a calendar.</p></div></div></section>
      <section className="blog-editorial" id="editorial"><div className="shell"><div className="blog-section-title"><div><p className="kicker">Permanent editorial hubs</p><h2>Explore the desks.</h2></div><p>Search the planned knowledge architecture. Article archives appear only as reviewed work is published.</p></div><EditorialExplorer /></div></section>
      <section className="blog-standards"><div className="shell"><div className="blog-standards-copy"><p className="kicker kicker--light">Editorial standard</p><h2>Authority is earned<br />one useful page at a time.</h2></div><div className="blog-standard-grid"><article><span>01</span><h3>Explain the system</h3><p>Show mechanisms, constraints, and tradeoffs instead of vague claims.</p></article><article><span>02</span><h3>Source the evidence</h3><p>Separate observation, inference, opinion, and verified fact.</p></article><article><span>03</span><h3>Write for people</h3><p>Serve the reader first while keeping content easy for machines to retrieve.</p></article><article><span>04</span><h3>Update honestly</h3><p>Show meaningful revisions and retire advice that no longer holds.</p></article></div></div></section>
      <section className="blog-applied"><div className="shell blog-applied-grid"><div><p className="kicker">Applied intelligence</p><h2>Start with the research already in use.</h2><p>SiteNexis publishes its methodology for measuring retrieval, AI visibility, and machine trust across a four-layer analysis stack.</p><a className="button" href={siteNexisLinks.methodology} data-analytics="blog-sitenexis-methodology">Read SiteNexis methodology <Arrow /></a></div><div className="blog-method-card"><span>Live methodology</span><strong>16 agents</strong><strong>12 scores</strong><strong>4 layers</strong><small>Public, explainable, and connected to a working product.</small></div></div></section>
      <section className="blog-newsletter"><div className="shell"><div><p className="kicker kicker--light">NexisHub dispatch</p><h2>New thinking,<br />when it is ready.</h2><p>Product, research, and engineering updates. No manufactured publishing cadence.</p></div><NewsletterForm /></div></section>
    </main><SiteFooter /></>;
}
